project:
  type: website
  output-dir: docs

website:
  title: "Intro to R"
  page-navigation: true
  sidebar:
    style: "floating"
    search: true
    number-sections: true
    collapse-level: 1
    contents:
      - section: "1. To do ahead of time"
        contents: 
          - install.qmd
          - code-of-conduct.qmd
          - benchmarks.qmd
      - section: "2. Introduction"
        contents:
          - file-location.qmd
          - r-overview.qmd
          - rstudio-orientation.qmd
      - section: "3. Coding in R"
        contents:
          - basic-syntax.qmd
          - data-types.qmd
          - packages-libraries.qmd
      - section: "4. Manipulations of data"
        contents:
          - importing-data.qmd
          - exporting-data.qmd
          - tidyverse-intro.qmd
      - section: "5. Data wrangling"
        contents:
          - StarWars.qmd
          - growthcurve.qmd
          - asvdata.qmd
      - section: "6. Data visualization"
        contents:
          - basic-plots.qmd
          - customize-plots.qmd
      - section: "7. Data analysis"
        contents:
          - clustering.qmd
          - correlation_linearregression.qmd
#          - lab-qualitativetable.qmd
#      - section: "8. What's next?"
#        contents:

format:
  html:
    theme: simplex
    css: styles.css
    toc: true



