---
title: "Welcome"
---

Introduction to the R programming language workshop.

**April 7th, 2023 9am-4:30pm**

Eller O&M 602 & hybrid (email instructor for Zoom link).

## Tentative schedule

-   9:00 AM

    -   Orientation in RStudio & introduction to R
    -   Basic syntax
    -   Data classes & data frames

-   9:55 - 10:00 AM *5 min break*

-   10:00 AM

    -   Data classes & data frames
    -   R packages
    -   Data import/export

-   11:00-11:10 AM *10 min break*

-   11:15 AM

    -   Introduction to tidyverse
    -   Continued tidyverse introduction

-   12:00 - 1:00 PM *lunch break (1 hour) & course check in*

-   1:00 PM

    -   Tidyverse & Star Wars
    -   Working with microbiome data
    -   Intro to plotting
    -   \**Data visualization practices*

-   2:00 - 2:05 PM *5 min break*

-   2:05

    -   Intro to plotting
    -   \**Ordination & clustering*
    -   \**Incorporate metadata*

-   3:05 - 3:15 PM *10 min break*

-   4:15 PM

    -   \**Data visualization practices*
    -   \**Data management practices*

    \**tentative topic*

## References & sources for course material

-   [R for Reproducible Scientific Analysis from Software Carpentry](https://swcarpentry.github.io/r-novice-gapminder/)
-   [Bioinformatics Virtual Coordination Network - R section](https://biovcnet.github.io) (also see youtube channel)
-   [Riffomonas](https://riffomonas.org/reproducible_research/)

## Required pre-requisite

-   Updated laptop (Mac or PC). Instructor will use a Mac
-   Internet connection
-   Fill out the [pre-course survey](https://forms.gle/32hw2zo3ukPmZjDd7)
-   Review the Code of Conduct

## Recommended preparation

-   Make sure R and RStudio are set up on your computer and working
-   Determine how to open up the Terminal on your computer
-   Come with questions on how you want to use R

## Course organization

This course is designed as a "crash course" that takes place only over a few days, in longer blocks of time. There will be frequent breaks. At any time raise your hand or use the 'raise hand' option remotely to ask a question.

Please note that learning R is similar to learning a whole new language. Additionally, we do not expect any prior experience for this course. Together, this means that each learner will have their own pace and experience during the course. Please be respectful of this and if you see how you can help someone, do so!

For instruction, we will be **live coding** the entire time. While most of the code is available on this website, the live coding aspect will help immerse you into coding in R. During each live coding session, the R script for each session will be saved and uploaded so you can access it in the future. This is because the code on this page is meant to be minimal, and during the coding sessions we will expand upon what is shown and document as we go along.

In order to keep a pulse on the pace of the class, please use the **raising hand acknowledgement** or the **post it note approach** to indicate to the instructor(s) that you need the content to slow down or you are stuck.

Since we are all learning together, we will also use the term **buddy up** to take a pause and ask your direct neighbors for help or come together with the people around you to troubleshoot the problem.

## Sessions archive

This course is meant to evolve over time, be re-taught, and referred to in the future. See the directory `introduction-to-R/sessions` to find the saved code from your session.

## Code of conduct

By participating in this course all participants are required to follow the [Code of Conduct].

*This text is adapted from guidelines written for The Carpentries Handbook. Additional language was added under a CC BY 3.0 license*
